### ISSUE TITLE
ERROR  IN : Building Promoter Regions for QC cd bed/ && Rscript promoter.R

### ISSUE THREAD

**Issue by zhuangfjnu** [tobiasrausch/ATACseq#1]
HI ,
When I cd bed/ && Rscript promoter.R
I get this information in R
Error in names(trackIds) <- sub("^ ", "", nms[nms != "new"]) : 

Any help for this error will be appreciated!

Thanks!

**Comment by tobiasrausch** [comment]
That was an [issue in the Bioconductor rtracklayer package](https://github.com/lawremi/rtracklayer/issues/4). If you updated to the latest version it should be fixed or if you are familiar with R you can also use the package TxDb.Hsapiens.UCSC.hg19.knownGene and get the promoter sequences from that package.

**Comment by YingziZhang-github** [comment]
Hi Tobias,
Is hg38 accessible when using ATACseq? I saw the usage options are "hg19|mm10".

**Comment by tobiasrausch** [comment]
A different genome build just requires a set of promoter regions and that [homer](http://homer.ucsd.edu/homer/) supports it. I have added this now for hg38.
