### ISSUE TITLE
The downloaded jaspar.zip seems not a zip file

### ISSUE THREAD

**Issue by Puriney** [tobiasrausch/ATACseq#2]
For the `motif/downloadMotifs.sh` script,

```
curl --output jaspar.zip 'http://jaspar.genereg.net/download/CORE/JASPAR2018_CORE_vertebrates_non-redundant_pfms_jaspar.zip'
```

It seems that the downloaded zip file is actually not a zip file. I manually downloaded the zip file and then the rest lines work.

**Comment by tobiasrausch** [comment]
Looks like jaspar updated the matrices to a new 2020 version. I have changed the download script. Should work now. Thanks for reporting this issue.
