### ISSUE TITLE
bowtie step

### ISSUE THREAD

**Issue by mdidish** [tobiasrausch/ATACseq#3]
Dear,
Thank you for this project for ATAC-Seq analyse.
I don't understand how Bowtie step could work, line 46 in align.sh:
`bowtie2 --threads ${THREADS} --local --maxins 2000 -x ${HG} -1 ${OUTP}.1.fq.gz -2 ${OUTP}.2.fq.gz 2> ${OUTP}.bowtie.log | samtools view -bT ${HG} - > ${OUTP}.raw.bam`

-x ${HG} requires a Bowtie index
-bT ${HG] requires a fasta file

So either I have a error of Bowtie2 `... does not exist or is not a Bowtie 2 index`

So what should I indicate as `<genome.fa>` argument in atac.sh? Or should I indicate the Bowtie index in align.sh?

Best,

**Comment by mdidish** [comment]
Another point, in align.sh, lines 63 and 72, I think that `hg19.promoter.bed.gz` should be remplaced by `${ATYPE}.promoter.bed.gz` to permit mm10 use if indicated?

**Comment by tobiasrausch** [comment]
Usually the FASTA file and the bowtie index are in the same directory. bowtie just expects the FASTA and then finds the corresponding index files automatically. Your 2nd point is fixed now, thanks for reporting.

**Comment by mdidish** [comment]
Thank you for your respone, I will try to put fasta file in bowtie index directory.

I think there is another typo in homer.sh line 28, `hg19` should be remplaced by `${HG}`?

Best,

**Comment by tobiasrausch** [comment]
I think I replaced this already.

**Comment by mdidish** [comment]
Ok sorry I didn't see the commit.

However you replaced `hg19` by `${ATYPE}`, then you have to pass this in arguments in file atac.sh line 51?
Or can we indicate the fasta file to annotatePeaks.pl, in this case we could replace `${ATYPE}` by `${HG}`?

**Comment by tobiasrausch** [comment]
That was too quick, sorry. I pass in now the analysis type.

**Comment by mdidish** [comment]
Thank you a lot for your fast response and updates!

Another point (the last I think): I have to run first
`perl /home/marc/Programs/ATAC/tobiasrausch/bin/envs/atac2/share/homer-4.9.1-6/.//configureHomer.pl -install mm10`
to run without error `annotatePeaks.pl` in homer.sh and `findMotifsGenome.pl` in motif.sh, otherwise I obtained an error message:
`!!!!Genome mm10 not found in /home/marc/Programs/ATAC/tobiasrausch/bin/envs/atac2/share/homer-4.9.1-6/.//config.txt
	To check if is available, run "perl /home/marc/Programs/ATAC/tobiasrausch/bin/envs/atac2/share/homer-4.9.1-6/.//configureHomer.pl -list"
	If so, add it by typing "perl /home/marc/Programs/ATAC/tobiasrausch/bin/envs/atac2/share/homer-4.9.1-6/.//configureHomer.pl -install mm10"`

Best,

**Comment by tobiasrausch** [comment]
I think that's true. The Makefile should show how to do it for hg19.

**Comment by mdidish** [comment]
I have a last question. In footprint.sh, you have a `if` condition before `alfred annotate` line 54, restricting its execution to hg19.

Yet it seems that there are some murine transcription factors in ./motif/jaspar.gz, could we also run `alfred annotate` for mm10?

**Comment by tobiasrausch** [comment]
To be honest, I never fully trusted this ATAC footprinting hypothesis. What makes sense in my opinion is to annotate the mm10 reference with murine transcription factor binding sites and then looking for overlaps with peaks and enrichment/depletion compared to a randomized background (shuffled peaks).

**Comment by mdidish** [comment]
ok thank you for all your responses.
