### ISSUE TITLE
Trim fastq.gz step issue

### ISSUE THREAD

**Issue by xchromosome219** [tobiasrausch/ATACseq#4]
Hi Trausch,

I wonder about one step (cut adapter step) in your pipeline. You set a specific "sequence" to remove the adapter, and I don't know whether this could affect the outcome (follow your pipeline). Is there any chance to take this step automatically or take our option?  

This is a great pipeline (ALL in one)!

Thanks,
Haitao

**Comment by tobiasrausch** [comment]
Sure, you can replace that step with a general purpose trimmer like trim_galore. That should be fine.

**Comment by xchromosome219** [comment]
Okay, Thanks!
Haitao
