### ISSUE TITLE
Issue with annotatePeak in ChIPseeker

### ISSUE THREAD

**Issue by gh909** [tobiasrausch/ATACseq#5]
Hi Tobias,

I am following your ATACseq tutorial and am currently at step 2.9 (Annotate genomic context).  I'm able to make the gr object from the data frame. However, when I try to use the annotatePeak function from Dr.Yu's ChIPseeker, I get the following error:

My code (from the tutorial):
> txdb <- TxDb.Hsapiens.UCSC.hg19.knownGene
> peakAnno <- annotatePeak(gr, tssRegion=c(-1000, 1000), TxDb=txdb, annoDb="org.Hs.eg.db", verbose=TRUE)

Terminal Output:
>> preparing features information...		 2021-12-08 03:28:04 PM 
>> identifying nearest features...		 2021-12-08 03:28:04 PM 
Error in which(strand(subject) != "-") : 
  argument to 'which' is not logical

I interrogated strand(gr) for the sample dataset in your tutorial:
factor-Rle of length 57891 with 1 run
  Lengths: 57891
  Values :     *
Levels(3): + - *

I wonder if the function is having trouble with the factor-Rle object. Are you able to help with this?

Many thanks,

George

**Comment by tobiasrausch** [comment]
Hi George,

Hmm, looks like ChIPseeker is now expecting something different for strand then *, + or -. I think that's something the ChIPseeker developers need to look at, I am sorry.

Best, Tobias
